services:
  # postgres services
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}

    restart: always
    volumes:
      - data_postgres:/var/lib/postgresql/data

  # Mongodb services
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  # Vending app
  vending_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vending_app
    environment:
      DATABASE_URL:  ${DATABASE_URL}
      MONGO_LOG_URL: ${MONGO_LOG_URL}
      PORT : 3000
      NODE_ENV : "development" 
      STOCK_OPNAME_JOB_ENABLED : false
      LOG_ENABLED : true
      MONGO_LOG_ENABLED : true
      HTTP_LOG_ENABLED : true
      MONGO_DB_LOG : ${MONGO_DB_LOG}
      
    ports:
      - "3000:3000"

    depends_on:
      - postgres
      - mongodb

    volumes:
      - .:/usr/app
volumes:
  data_postgres:
  data_mongo: